### ISSUE TITLE
Confusion About the Meaning of the ‘minted’ and ‘total_mints’ Columns

### ISSUE THREAD

**Issue by GregorWedlich** [hirosystems/runehook#42]
I’m a bit confused! The columns “minted” and “total_mints” are always the same.

I thought the “minted” column shows the number of mints per block, and “total_mints” shows the current total across all blocks?

![Image](https://github.com/user-attachments/assets/de140fd4-49d1-452c-872f-46d72d19fcbc)
![Image](https://github.com/user-attachments/assets/1ca2fa3d-97d6-414a-8fc6-51e7c768fb4e)

**Comment by rafaelcr** [comment]
> I thought the “minted” column shows the number of mints per block, and “total_mints” shows the current total across all blocks?

`minted` shows how much balance of that rune has been minted so far, while `total_mints` shows how many mint operations have happened. However, since you're lookint at the `UNCOMMONGOODS` rune which only allows minting 1 whole token per operation, those values are always the same.

Take a look at other tokens that allow minting more than 1 and you'll see the difference.

Let me know if you have further questions.

**Comment by GregorWedlich** [comment]
This makes a lot of sense! Thanks :)
